//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppraisalDbContext : DbContext
    {
        public AppraisalDbContext()
            : base("name=AppraisalDbContext")
        {
    	this.Configuration.LazyLoadingEnabled = false;
    	this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPETENCE> COMPETENCES { get; set; }
        public virtual DbSet<EVALUATION_TEMPLATES> EVALUATION_TEMPLATES { get; set; }
        public virtual DbSet<EVALUATION> EVALUATIONS { get; set; }
        public virtual DbSet<POSITION> POSITIONS { get; set; }
        public virtual DbSet<QUESTION> QUESTIONS { get; set; }
        public virtual DbSet<RATING> RATINGS { get; set; }
        public virtual DbSet<RESULT> RESULTS { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
